export enum ActionTypesCharacters {
  LOAD_CHARACTERS = 'LOAD_CHARACTERS',
  GET_CHARACTERS = 'GET_CHARACTERS',
  ERROR_GET_CHARACTERS = 'ERROR_GET_CHARACTERS',
}

export enum ActionTypesComics {
  LOAD_COMICS = 'LOAD_COMICS',
  GET_COMICS = 'GET_COMICS',
  ERROR_GET_COMICS = 'ERROR_GET_COMICS',
}
