export const LOAD_CHARACTERS = 'LOAD_CHARACTERS';
export const GET_CHARACTERS = 'GET_CHARACTERS';
export const ERROR_GET_CHARACTERS = 'ERROR_GET_CHARACTERS';
export const LOAD_COMICS = 'LOAD_COMICS';
export const GET_COMICS = 'GET_COMICS';
export const ERROR_GET_COMICS = 'ERROR_GET_COMICS';
